routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\BookController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Dashboard route
 * @index
 */
Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

/**
 * Author resource routes
 * @index
 * @store
 * @create
 * @show
 * @update
 * @destroy
 * @edit
 */
Route::resource('authors', AuthorController::class);

/**
 * Book resource routes
 * @index
 * @store
 * @create
 * @show
 * @update
 * @destroy
 * @edit
 */
Route::resource('books', BookController::class);

Route::prefix('books')->group(function () {
    Route::get('/lend-book/{book}', [BookController::class, 'lendBook'])->name('books.lend');
    Route::get('/return-book/{book}', [BookController::class, 'returnBook'])->name('books.return');
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'is_borrowed',
    ];

    // RELATIONS
    
    public function author()
    {
        return $this->belongsTo(Author::class, 'author_id', 'id');
    }
    
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Book;
use App\Models\Author;
use App\Http\Requests\StoreBook;
use App\Http\Requests\UpdateBook;
use Illuminate\Support\Collection;

class BookController extends Controller
{
    /**
     * Change state of specific book to 'borrowed' (is_borrowed = 1)
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function lendBook($id)
    {
        if (!$book = Book::find($id)) {
            return redirect()->back()->with('status', 'Kniha sa nenasla');
        }

        if ($book->is_borrowed) {
            return redirect()->back()->with('status', 'Kniha je uz pozicana');
        }

        $book->is_borrowed = true;
        $book->save();
        
        return redirect()->back()->with('status', 'Kniha bola pozicana');
    }

    /**
     * Change state of specific book to 'returned' (is_borrowed = 0)
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function returnBook($id)
    {
        if (!$book = Book::find($id)) {
            return redirect()->back()->with('status', 'Kniha sa nenasla');
        }

        if (!$book->is_borrowed) {
            return redirect()->back()->with('status', 'Kniha je uz vratena');
        }

        $book->is_borrowed = false;
        $book->save();
        
        return redirect()->back()->with('status', 'Kniha bola vratena');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = [
            'title' => 'Zoznam knih',
            'description' => 'Zoznam knih',
            'books' => $this->sortedBooks($request),
        ];

        return view('pages.book.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $data = [
            'title' => 'Vytvorit knihu',
            'description' => 'Vytvorenie knihu',
            'routeUrl' => route('books.store'),
            'formMethod' => null,
            'book' => new Book(),
            'authors' => Author::get(),
            'author_id' => $request->query('author_id'),
        ];

        return view('pages.book.createOrEdit',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBook $request)
    {
        $data = $request->validated();
        $author = Author::find($data['author_id']);

        $book = new Book;
        $book->title =  $data['title'];
        $book->is_borrowed = false;
        $book->author()->associate($author);
        $book->save();

        return redirect()->route('books.index')->with('status', 'Kniha bola vytvorena');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = [
            'title' => 'Detail knihy',
            'description' => 'Detaily knihy',
            'book' => Book::find($id),
        ];

        return view('pages.book.show',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [
            'title' => 'Upravit knihu',
            'description' => 'Uprava knihu',
            'routeUrl' => route('books.update',['book' => $id]),
            'formMethod' => '<input type="hidden" name="_method" value="PUT">',
            'book' => Book::find($id),
            'authors' => Author::get(),
        ];

        return view('pages.book.createOrEdit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBook $request, $id)
    {
        if (!$book = Book::find($id)) {
            return redirect()->route('books.index')->with('status', 'Kniha sa nenasla');
        }

        try {

            $data = $request->validated();
            $author = Author::find($data['author_id']);

            $book->title =  $data['title'];
            $book->author()->associate($author);
            $book->save();
            return redirect()->route('books.index')->with('status', 'Kniha bola upravena');

        } catch (\Throwable $th) {

            return redirect()->route('books.index')->with('status', 'Knihu sa nepodarilo upravit');
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!$book = Book::find($id)) {
            return redirect()->route('books.index')->with('status', 'Kniha sa nenasla');
        }

        try {

            $book->delete();
            return redirect()->route('books.index')->with('status', 'Kniha bola zmazana');

        } catch (\Throwable $th) {
            
            return redirect()->route('books.index')->with('status', 'Knihu sa nepodarilo vymazat');
        }

    }

    /**
     * Return sorted books. 
     * @param Request $request 
     * @return Collection of Book
     */
    protected function sortedBooks(Request $request) : Collection
    {
        $sortable = [
            'title',
            'author',
            'is_borrowed',
        ];

        $sort = $request->query('sort');
        $order = $request->query('order');

        if (!in_array($sort, $sortable)) {
            return Book::with('author')->get();
        }

        if ($order == 'asc' || $order == 'desc') {
            
            if ($sort == 'author') {
                return Book::with(['author' => function ($query) use ($order) {
                    $query->orderBy('name', $order);
                }])->get();
            }

            return Book::with('author')->orderBy($sort, $order)->get();
        }
    }
}

resources/views/pages/book/createOrEdit.blade.php
@extends('layouts.default')

@section('title', $title)
@section('description', $description)

@section('content')
    @if ($book)
        <form action="{{ $routeUrl }}" method="POST" enctype="application/x-www-form-urlencoded">
            <h1>{{ $title }}</h1>
            @csrf
            {!! $formMethod !!}
            <div class="form-group">
                <label for="title">Titul</label>
                <input type="text" class="form-control" id="title" name="title" placeholder="Titul knihy" value="{{old('title') ?? $book->title ?? ''}}">
                @if($errors->has('title'))
                    <small class="form-text alert alert-danger">{{ $errors->first('title') }}</small>
                @endif
            </div>
            <div class="form-group">
                <label for="author">Autor knihy</label>
                <select class="form-control" id="author_id" name="author_id">
                    <option value="0">--vyberte--</option>
                    @foreach ($authors as $author)
                    <option value="{{$author->id}}" @if( (isset($author_id) && $author_id == $author->id) || old('author_id') == $author->id || optional($book->author)->id == $author->id) selected @endif >{{$author->fullName}}</option>
                    @endforeach
                </select>
                @if($errors->has('author_id'))
                    <small class="form-text alert alert-danger">{{ $errors->first('author_id') }}</small>
                @endif
            </div>

            <button type="submit" class="btn btn-primary">Ulozit knihu</button>
        </form>
    @else
        <div class="alert alert-primary">
            Kniha sa nenasla
        </div>
    @endif
@stop

resources/views/pages/book/index.blade.php
@extends('layouts.default')

@section('title', $title)
@section('description', $description)

@section('content')
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif

    <table class="table" id="indexTable">
        <caption>{{$title}}</caption>
        <tr>
            <th>
                Titul
                <a href="?sort=title&order=desc" title="zoradit vzostupne"><i class="fas fa-sort-up"></i></a>
                <a href="?sort=title&order=asc" title="zoradit zostupne"><i class="fas fa-sort-down"></i></a>
            </th>
            <th>
                Meno autora
                <a href="?sort=author&order=desc" title="zoradit vzostupne"><i class="fas fa-sort-up"></i></a>
                <a href="?sort=author&order=asc" title="zoradit zostupne"><i class="fas fa-sort-down"></i></a>
            </th>
            <th>
                Je zapozicana
                <a href="?sort=is_borrowed&order=desc" title="zoradit vzostupne"><i class="fas fa-sort-up"></i></a>
                <a href="?sort=is_borrowed&order=asc" title="zoradit zostupne"><i class="fas fa-sort-down"></i></a>
            </th>
            <th>
                Akcie
            </th>
        </tr>
        
        {{-- add new book action --}}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <a href="{{route('books.create')}}">Pridat knihu</a>
            </td>
        </tr>

        {{-- list books --}}
        @foreach ($books as $book)
        <tr>
            <td>{{$book->title}}</td>
            <td><a href="{{route('authors.show',['author' => $book->author->id])}}">{{$book->author->fullName}}</a></td>
            <td>{{$book->is_borrowed ? 'Ano' : 'Nie'}}</td>
            <td>
                <a href="{{route('books.show', ['book' => $book->id])}}" title="zobrazit knihu"><i class="fas fa-eye"></i></a>

                &nbsp;

                <a href="{{route('books.edit', ['book' => $book->id])}}" title="upravit knihu"><i class="fas fa-edit"></i></a>

                &nbsp;

                @if ($book->is_borrowed)
                <a href="{{route('books.return',['book' => $book->id])}}" title="vratit knihu"><i class="fas fa-arrow-alt-circle-down"></i></a>
                @else
                <a href="{{route('books.lend',['book' => $book->id])}}" title="pozicat knihu"><i class="fas fa-arrow-alt-circle-up"></i></a>
                @endif

                &nbsp;
                
                <i class="fas fa-trash" data-url="{{route('books.destroy',['book' => $book->id])}}" title="zmazat knihu"></i>
            </td>
        </tr>
        @endforeach
    </table>
@stop

@push('scripts')
    <script>
        {{--  
            Add event listner on table element for book deletion.
        --}}
        (function() {
            function confirmDelete()
            {
                if ( !event.target.classList.contains("fa-trash") ) {
                    return;
                }

                const url = event.target.dataset.url;
                if (typeof url === "undefined") {
                    return;
                }

                if (confirm('Kniha bude vymazana. Pokracovat?')) {
                    const form = document.createElement("FORM");
                    form.action = url;
                    form.enctype = "application/x-www-form-urlencoded";
                    form.method = "post";
    
                    const deleteInputField = document.createElement("INPUT");
                    deleteInputField.setAttribute("type","hidden");
                    deleteInputField.name = "_method";
                    deleteInputField.value = "DELETE";
                    form.appendChild(deleteInputField);
    
                    const csrfTokenInputField = document.createElement("INPUT");
                    csrfTokenInputField.setAttribute("type","hidden");
                    csrfTokenInputField.name = "_token";
                    csrfTokenInputField.value = "{{csrf_token()}}";
                    form.appendChild(csrfTokenInputField);
    
                    document.body.appendChild(form);
                    form.submit();
                }
            }
            
            const table = document.getElementById("indexTable")
            table.addEventListener("click", confirmDelete, false);

        })();
       
    </script>
@endpush

resources/views/pages/book/show.blade.php
@extends('layouts.default')

@section('title', $title)
@section('description', $description)

@section('content')
    @if($book)
        <h1>{{ $book->title }}</h1>
        
        <b>Stav:</b> {{ ($book->is_borrowed) ? 'Zapozicana' : 'Dostupna'}} <br/>
        <b>Autor:</b> {{ $book->author->fullName }} <br/>
        
    @else 
    <div class="alert alert-primary">
        Kniha sa nenasla
    </div>
    @endif
@stop