routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\BookController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Dashboard route
 * @index
 */
Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

/**
 * Author resource routes
 * @index
 * @store
 * @create
 * @show
 * @update
 * @destroy
 * @edit
 */
Route::resource('authors', AuthorController::class);

/**
 * Book resource routes
 * @index
 * @store
 * @create
 * @show
 * @update
 * @destroy
 * @edit
 */
Route::resource('books', BookController::class);

Route::prefix('books')->group(function () {
    Route::get('/lend-book/{book}', [BookController::class, 'lendBook'])->name('books.lend');
    Route::get('/return-book/{book}', [BookController::class, 'returnBook'])->name('books.return');
});

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'surname',
    ];

    // RELATIONS

    
    public function books()
    {
        return $this->hasMany(Book::class, 'author_id', 'id');
    }

    // METHODS

    /**
     * Get count of all books that belongs to this author.
     * @return int;
     */
    public function getBooksCount() : int
    {
        return $this->books->count();
    }
    
    public function getFullNameAttribute() : string
    {
        return "{$this->name} {$this->surname}";
    }
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Author;
use App\Http\Requests\StoreAuthor;
use App\Http\Requests\UpdateAuthor;
use Illuminate\Support\Collection;


class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = [
            'title' => 'Zoznam autorov',
            'description' => 'Zoznam autorov',
            'authors' => $this->sortedAuthors($request),
        ];

        return view('pages.author.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'title' => 'Vytvorit autora',
            'description' => 'Vytvorenie autora',
            'routeUrl' => route('authors.store'),
            'formMethod' => null,
            'author' => new Author(),
        ];

        return view('pages.author.createOrEdit',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAuthor $request)
    {
        $author = Author::create($request->validated());
        $author->save();

        return redirect()->route('authors.index')->with('status', 'Autor bol vytvoreny');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = [
            'title' => 'Detail autora',
            'description' => 'Detaily autora',
            'author' => Author::with('books')->find($id),
        ];

        return view('pages.author.show',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [
            'title' => 'Upravit autora',
            'description' => 'Uprava autora',
            'routeUrl' => route('authors.update',['author' => $id]),
            'formMethod' => '<input type="hidden" name="_method" value="PUT">',
            'author' => Author::find($id),
        ];

        return view('pages.author.createOrEdit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAuthor $request, $id)
    {
        if (!$author = Author::find($id)) {
            return redirect()->route('authors.index')->with('status', 'Autor sa nenasiel');
        }

        try {

            $author->update($request->validated());
            return redirect()->route('authors.index')->with('status', 'Autor bol upraveny');

        } catch (\Throwable $th) {

            return redirect()->route('authors.index')->with('status', 'Autora sa nepodarilo upravit');
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!$author = Author::find($id)) {
            return redirect()->route('authors.index')->with('status', 'Autor sa nenasiel');
        }

        try {

            $author->delete();
            return redirect()->route('authors.index')->with('status', 'Autor bol zmazany');

        } catch (\Throwable $th) {
            
            return redirect()->route('authors.index')->with('status', 'Autora sa nepodarilo vymazat');
        }

    }

    /**
     * Return sorted authors. 
     * @param Request $request 
     * @return Collection of Author
     */
    protected function sortedAuthors(Request $request) : Collection
    {
        $sortable = [
            'name',
            'surname',
            'count',
        ];

        $sort = $request->query('sort');
        $order = $request->query('order');

        if (!in_array($sort, $sortable)) {
            return Author::with('books')->get();
        }

        if ($order == 'asc' || $order == 'desc') {
            
            if ($sort == 'count') {
                return Author::with('books')->withCount('books')->orderBy('books_count', $order)->get();
            }

            return Author::with('books')->orderBy($sort, $order)->get();
        }
    }
}

resources/views/pages/author/createOrEdit.blade.php
@extends('layouts.default')

@section('title', $title)
@section('description', $description)

@section('content')
    @if ($author)
        <form action="{{ $routeUrl }}" method="POST" enctype="application/x-www-form-urlencoded">
            <h1>{{ $title }}</h1>
            @csrf
            {!! $formMethod !!}
            <div class="form-group">
                <label for="name">Meno</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Meno autora" value="{{old('name') ?? $author->name ?? ''}}">
                @if($errors->has('name'))
                    <small class="form-text alert alert-danger">{{ $errors->first('name') }}</small>
                @endif
            </div>
            <div class="form-group">
                <label for="surname">Priezvisko</label>
                <input type="text" class="form-control" id="surname" name="surname" placeholder="Priezvisko autora" value="{{ old('surname') ?? $author->surname ?? '' }}">
                @if($errors->has('surname'))
                    <small class="form-text alert alert-danger">{{ $errors->first('surname') }}</small>
                @endif
            </div>

            <button type="submit" class="btn btn-primary">Ulozit autora</button>
        </form>
    @else
        <div class="alert alert-primary">
            Autor sa nenasiel
        </div>
    @endif

@stop

resources/views/pages/author/index.blade.php
@extends('layouts.default')

@section('title', $title)
@section('description', $description)

@section('content')
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif

    <table class="table" id="indexTable">
        <caption>{{$title}}</caption>
        <tr>
            <th>
                Meno
                <a href="?sort=name&order=desc" title="zoradit vzostupne"><i class="fas fa-sort-up"></i></a>
                <a href="?sort=name&order=asc" title="zoradit zostupne"><i class="fas fa-sort-down"></i></a>
            </th>
            <th>
                Priezvisko
                <a href="?sort=surname&order=desc" title="zoradit vzostupne"><i class="fas fa-sort-up"></i></a>
                <a href="?sort=surname&order=asc" title="zoradit zostupne"><i class="fas fa-sort-down"></i></a>
            </th>
            <th>
                Pocet knih
                <a href="?sort=count&order=desc" title="zoradit vzostupne"><i class="fas fa-sort-up"></i></a>
                <a href="?sort=count&order=asc" title="zoradit zostupne"><i class="fas fa-sort-down"></i></a>
            </th>
            <th>
                Akcie
            </th>
        </tr>
        
        {{-- add new author action --}}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <a href="{{route('authors.create')}}">Pridat autora</a>
            </td>
        </tr>

        {{-- list authors --}}
        @foreach ($authors as $author)
        <tr>
            <td>{{$author->name}}</td>
            <td>{{$author->surname}}</td>
            <td>{{$author->getBooksCount()}}</td>
            <td>
                <a href="{{route('authors.show', ['author' => $author->id])}}" title="zobrazit autora"><i class="fas fa-eye"></i></a>

                &nbsp;

                <a href="{{route('authors.edit', ['author' => $author->id])}}" title="upravit autora"><i class="fas fa-edit"></i></a>

                &nbsp;

                <a href="{{route('books.create',['author_id' => $author->id])}}" title="pridat knihu"><i class="fas fa-plus"></i></a>

                &nbsp;
                
                <i class="fas fa-trash" data-url="{{route('authors.destroy',['author' => $author->id])}}" title="zmazat autora"></i>
            </td>
        </tr>
        @endforeach
    </table>
@stop

@push('scripts')
    <script>
        {{--  
            Add event listner on table element for author deletion.
        --}}
        (function() {
            function confirmDelete()
            {
                if ( !event.target.classList.contains("fa-trash") ) {
                    return;
                }

                const url = event.target.dataset.url;
                if (typeof url === "undefined") {
                    return;
                }

                if (confirm('Autor bude vymazany. Pokracovat?')) {
                    const form = document.createElement("FORM");
                    form.action = url;
                    form.enctype = "application/x-www-form-urlencoded";
                    form.method = "post";
    
                    const deleteInputField = document.createElement("INPUT");
                    deleteInputField.setAttribute("type","hidden");
                    deleteInputField.name = "_method";
                    deleteInputField.value = "DELETE";
                    form.appendChild(deleteInputField);
    
                    const csrfTokenInputField = document.createElement("INPUT");
                    csrfTokenInputField.setAttribute("type","hidden");
                    csrfTokenInputField.name = "_token";
                    csrfTokenInputField.value = "{{csrf_token()}}";
                    form.appendChild(csrfTokenInputField);
    
                    document.body.appendChild(form);
                    form.submit();
                }
            }
            
            const table = document.getElementById("indexTable")
            table.addEventListener("click", confirmDelete, false);

        })();
       
    </script>
@endpush

resources/views/pages/author/show.blade.php
@extends('layouts.default')

@section('title', $title)
@section('description', $description)

@section('content')
    @if($author)
        <h1>{{$author->name}}&nbsp;{{$author->surname}}</h1>
        
        <h2>Zoznam knih:</h2>
        <ul>
            @foreach ($author->books as $book)
            <li><a href="{{route('books.show',['book' => $book->id])}}">{{$book->title}}</li>
            @endforeach
        </ul>
    @else 
    <div class="alert alert-primary">
        Autor sa nenasiel
    </div>
    @endif
@stop